export interface DistrictLocation {
  name: string;
  district: string;
  thana: string[];
}

/** Full Bangladesh district → thana/upazila list (ported from glowly-frontend). */
export const allLocation = (): DistrictLocation[] => {
  return [
    {
      name: "bagerhat",
      district: "Bagerhat",
      thana: [
        "Bagerhat Sadar",
        "Chitalmari",
        "Fakirhat",
        "Kachu Updazilla",
        "",
      ],
    },
    {
      name: "bandarban",
      district: "Bandarban",
      thana: [
        "Ali Kadam",
        "Bandarban Sadar",
        "Lama",
        "Naikhongchari",
        "Rowangchhari",
        "Ruma",
        "Thanchi",
      ],
    },
    {
      name: "barguna",
      district: "Barguna",
      thana: [
        "Amtali",
        "Bamna",
        "Barguna Sadar",
        "Betagi",
        "Patharghata",
        "Taltali",
      ],
    },
    {
      name: "barishal",
      district: "Barishal",
      thana: [
        "Agailjhara",
        "Babuganj",
        "Bakerganj",
        "Banaripara",
        "Barishal Sadar",
        "Gouronadi",
        "Hizla",
        "Mehendiganj",
        "Muladi",
        "Wazirpur",
      ],
    },
    {
      name: "bhola",
      district: "Bhola",
      thana: [
        "Bhola Sadar",
        "Borhanuddin",
        "Char Fassan",
        "Daulatkhan",
        "Lalmohan",
        "Manpura",
        "Tazumuddin",
      ],
    },
    {
      name: "bogra",
      district: "Bogra",
      thana: [
        "Alamdighi",
        "Baropur (Bogura)",
        "Bogura Sadar",
        "Dhunat",
        "Dhupchancia",
        "Gabtoli",
        "Kahaloo",
        "Nandigram",
        "Saraikandi",
        "Sherpur",
        "Shibganj",
        "Sonatola",
      ],
    },
    {
      name: "brahmanbaria",
      district: "Brahmanbaria",
      thana: [
        "Akhaura",
        "Ashuganj",
        "Bancharampur",
        "Brahmanbaria Sadar",
        "Kasba",
        "Nabinagar",
        "Nabinagar Bazar",
        "Nasirnagar",
        "Sarail",
      ],
    },
    {
      name: "chandpur",
      district: "Chandpur",
      thana: [
        "Chandpur Sadar",
        "Dhakirgaon",
        "Faridganj",
        "Haimchar",
        "Hajiganj",
        "Kachua",
        "Matlab North",
        "Matlab Dokkhin",
        "Shahrasti",
      ],
    },
    {
      name: "chapainawabganj",
      district: "Chapainawabganj",
      thana: [
        "Bholahat",
        "Chapainawabganj Sadar",
        "Gamastapur",
        "Nachole",
        "Shibganj Sadar",
      ],
    },
    {
      name: "chattogram",
      district: "Chattogram",
      thana: [
        "Akbar Shah",
        "Anwara",
        "Bakolia",
        "Bandar CTG",
        "Banshkhali",
        "Bayazid Bostami",
        "Baolkhali",
        "CEPZ",
        "Chandanaish",
        "Chandgaon",
        "Chawk Bazar",
        "Chattogram Sadar",
        "Doublemooring",
        "Fatikchari",
        "Halishahar",
        "Hathazari",
        "Karnaphuli",
        "KeraniHat",
        "Khulshi",
        "Kotwali - CTG",
        "Lohagara",
        "Mirsharai",
        "Pahartali",
        "Panchlaish",
        "Potenga",
        "Patiya",
        "Rangunia",
        "Raozan",
        "Sadarghat - CTG",
        "Sandwip",
        "Satkania",
        "Shantirhat (Patiya)",
        "Shantirhat (Patiya) - CTG",
        "Sitakunda",
        "Sitakunda (Citygat)",
      ],
    },
    {
      name: "cumilla",
      district: "Cumilla",
      thana: [
        "Bangora Bazar",
        "Barura",
        "Brahmanpara",
        "Burichang",
        "Chandina",
        "Chauddagram",
        "Cumilla Sadar South Model",
        "Daudkandi",
        "Debidwar",
        "Hamna",
        "Kandirpar",
        "Kotwali Model",
        "Laksam",
        "Lalmai",
        "Meghna",
        "Monoharganj",
        "Muradnagar",
        "Nangalkot",
        "Titas",
      ],
    },
    {
      name: "cox's Bazar",
      district: "Cox's Bazar",
      thana: [
        "Chakaria",
        "Cox's Bazar Sadar",
        "Eidgaon",
        "Kutubdia",
        "Moheskhali",
        "Pekua",
        "Ramu",
        "Teknaf",
        "Ukhiya",
      ],
    },
    {
      name: "dhaka",
      district: "Dhaka City",
      thana: [
        "Adabor",
        "Airport",
        "Ati Bazar (Keraniganj)",
        "Azompur",
        "Badda",
        "Banani",
        "Bangshal",
        "Bashundhara R/A",
        "Bhashantek",
        "Cantonment",
        "Chawkbazar",
        "Dakshin Khan",
        "Darus Salam",
        "Demra",
        "Dhanmondi",
        "Gandaria",
        "Gulistan",
        "Gulshan",
        "Hatirjheel",
        "Hazaribag",
        "Jattrabari",
        "Kadamtali",
        "Kafrul",
        "Kalabagan",
        "Kamrangirchar",
        "Khilgaon",
        "Khilkhet",
        "Kotwali",
        "Lalbagh",
        "Mirpur",
        "Mohammadpur",
        "Motijheel",
        "Mugda",
        "New Market",
        "Pallabi",
        "Paltan",
        "Panthapath",
        "Purbachal",
        "Ramna",
        "Rampura",
        "Rupnagar",
        "Sabujbag",
        "Shah Ali",
        "Shah Ali Market",
        "Shahbag",
        "Shahjahanpur",
        "Sher-e-Bangla Nagar",
        "Shyampur",
        "Sutrapur",
        "Tejgaon",
        "Tejgaon Industrial Area",
        "Turag",
        "Uttara",
        "Uttarkhan",
        "Vasantek",
        "Vatara",
        "Wari",
      ],
    },
    {
      name: "dhaka sub-urban",
      district: "Dhaka Sub-Urban",
      thana: [
        "Ashulia",
        "Dhamrai",
        "Dohar",
        "Hemayetpur",
        "Keraniganj Model",
        "Nawabganj",
        "Savar",
        "South Keraniganj",
      ],
    },
    {
      name: "dinajpur",
      district: "Dinajpur",
      thana: [
        "Biral",
        "Birampur",
        "Birganj",
        "Bochaganj",
        "Chirrirbandar",
        "Dinajpur Sadar",
        "Fulbari",
        "Ghoraghat",
        "Hakimpur",
        "Kaharole",
        "Khansama",
        "Nawabganj Upazila",
        "Parbatipur",
      ],
    },
    {
      name: "faridpur",
      district: "Faridpur",
      thana: [
        "Alfadanga",
        "Bhaga",
        "Boalmari",
        "Charbhadrasan",
        "Faridpur",
        "Faridpur Sadar",
        "Madhukhali",
        "Nagarkanda",
        "Sadarpur",
        "Shaltha",
      ],
    },
    {
      name: "feni",
      district: "Feni",
      thana: [
        "Chagalnaiya",
        "Dagunbhuiyan",
        "Feni Sadar",
        "Fulgazi",
        "Parshuram",
        "Sonagazi",
      ],
    },
    {
      name: "gaibandha",
      district: "Gaibandha",
      thana: [
        "Fulchari",
        "Gabindaganj",
        "Gaibandha Sadar",
        "Palashbari",
        "Sadullapur",
        "Saghata",
        "Sundarganj",
      ],
    },
    {
      name: "gazipur",
      district: "Gazipur",
      thana: [
        "Gazipur Sadar",
        "Joydebpur",
        "Kaliakair Upazila",
        "Kaliganj Upazila",
        "Kapasia",
        "Kashimpur",
        "Kashimpur",
        "Rajendrapur",
        "Sreepur",
        "Tongi",
      ],
    },
    {
      name: "gopalganj",
      district: "Gopalganj",
      thana: [
        "Boultali",
        "Gopalganj",
        "Gopalganj Sadar",
        "Kasiani",
        "Kotalipara",
        "Muksudpur",
        "Tungipara",
      ],
    },
    {
      name: "habiganj",
      district: "Habiganj",
      thana: [
        "Ajmiriganj",
        "Bahubal",
        "Baniachong",
        "Chunarughat",
        "Habiganj Sadar",
        "Lakhai",
        "Madhobpur",
        "Nabiganj",
        "Null",
        "Shayestaganj",
      ],
    },
    {
      name: "jamalpur",
      district: "Jamalpur",
      thana: [
        "Baksiganj",
        "Dewanganj",
        "Islampur",
        "Jamalpur Sadar",
        "Madarganj",
        "Melandaha",
        "Nandina",
        "Sarishabari",
      ],
    },
    {
      name: "jashore",
      district: "Jashore",
      thana: [
        "Abhaynagar",
        "Bagharpara",
        "Chaugacha",
        "Jashore Sadar",
        "Jhikorgacha",
        "Keshobpur",
        "Manirampur",
        "Sharsha",
      ],
    },
    {
      name: "jhalokati",
      district: "Jhalokati",
      thana: ["Jhalokati Sadar", "Kathalia", "Nalchity", "Rajapur"],
    },
    {
      name: "jhenaidah",
      district: "Jhenaidah",
      thana: [
        "Harinakunda",
        "Jhenaidah Sadar",
        "Kaliganj",
        "Kotchandpur",
        "Maheshpur",
        "Shailkupa",
      ],
    },
    {
      name: "joypurhat",
      district: "Joypurhat",
      thana: ["Akkelpur", "Joypurhat Sadar", "Kalai", "Khetlal", "Panchbibi"],
    },
    {
      name: "khagrachori",
      district: "Khagrachori",
      thana: [
        "Dighinala",
        "Guimara",
        "Laxmichari",
        "Khagrachori Sadar",
        "Mahalchari",
        "Manikchari",
        "Matiranga",
        "Panchari",
        "Ramgarh",
      ],
    },
    {
      name: "Khulna",
      district: "Khulna",
      thana: [
        "Batiaghata",
        "Dacop",
        "Dighalia",
        "Khulna Sadar",
        "Dumuria",
        "Koyra",
        "Paikgacha",
        "Pultala",
        "Rupsha",
        "Terokhada",
      ],
    },
    {
      name: "Kishoreganj",
      district: "Kishoreganj",
      thana: [
        "Austagram",
        "Bajitpur",
        "Bhairab",
        "Hossainpur",
        "Itna",
        "Karimganj",
        "Katiadi",
        "Kishoreganj Sadar",
        "Kuliarchar",
        "Mithamain",
        "Nikli",
        "Pakundia",
        "Tarail",
      ],
    },
    {
      name: "Kurigram",
      district: "Kurigram",
      thana: [
        "Bhurungamri",
        "Char Rajibpur",
        "Chilmari",
        "Fulbari",
        "Nageshwari",
        "Rajarhat",
        "Raomari",
        "Kurigram Sadar",
        "Ulipur",
      ],
    },
    {
      name: "Kushtia",
      district: "Kushtia",
      thana: [
        "Bheramara",
        "Kushtia Sadar",
        "Daulatpur",
        "Khoksa",
        "Kumarkhali",
        "Mirpur Upazila",
      ],
    },
    {
      name: "Lalmonirhat",
      district: "Lalmonirhat",
      thana: [
        "Aditmari",
        "Lalmonirhat Sadar",
        "Hatibanda",
        "Kaliganj Sadar",
        "Patgram",
      ],
    },
    {
      name: "Laxmipur",
      district: "Laxmipur",
      thana: [
        "Chandraganj",
        "Laxmipur Sadar",
        "Kamalnagar",
        "Raipur",
        "Ramganj",
        "Ramgati",
      ],
    },
    {
      name: "Madaripur",
      district: "Madaripur",
      thana: ["Dasar", "Madaripur Sadar", "Kalkini", "Rajoir", "Shibchar"],
    },
    {
      name: "Magura",
      district: "Magura",
      thana: [
        "Mohammadpur Upazila",
        "Magura Sadar",
        "Shalikha",
        "Sreepur Upazila",
      ],
    },
    {
      name: "Manikganj",
      district: "Manikganj",
      thana: [
        "Daulatpur Upazila",
        "Manikganj Sadar",
        "Ghior",
        "Harirampur",
        "Saturia",
        "Shivalaya",
        "Singair",
      ],
    },
    {
      name: "Meherpur",
      district: "Meherpur",
      thana: ["Gangni", "Meherpur Sadar", "Mujibnagar"],
    },
    {
      name: "Moulivibazar",
      district: "Moulivibazar",
      thana: [
        "Barlekha",
        "Moulivibazar Sadar",
        "Barlekha (Moulivibazar)",
        "Juri",
        "Kamalganj",
        "Kulaura",
        "Rajnagar",
        "Sherpur (Moulivibazar), Sreemangal",
      ],
    },
    {
      name: "Munshiganj",
      district: "Munshiganj",
      thana: [
        "Gazaria",
        "Munshiganj Sadar",
        "Louhaganj",
        "Sirajdikhan",
        "Sreenagar",
        "Tongibari",
      ],
    },
    {
      name: "Mymensingh",
      district: "Mymensingh",
      thana: [
        "Bhaluka",
        "Mymensingh Sadar",
        "Dhobaura",
        "Fulbaria",
        "Gafargaon",
        "Gauripur",
        "Haluaghat",
        "Ishwarganj",
        "Muktagacha",
        "Nandail",
        "Pagla",
        "Phulpur",
        "Tarakanda",
        "Trishal",
      ],
    },
    {
      name: "Naogaon",
      district: "Naogaon",
      thana: [
        "Atrai",
        "Naogaon Sadar",
        "Badolgachi",
        "Dhamoirhat",
        "Manda",
        "Mohadebpur",
        "Niamatpur",
        "Patnitola",
        "Porsha",
        "Raninagar",
        "Sapahar",
      ],
    },
    {
      name: "Narail",
      district: "Narail",
      thana: ["Kalia", "Narail Sadar", "Lohagara"],
    },
    {
      name: "Narayanganj",
      district: "Narayanganj",
      thana: [
        "Araihajar",
        "Narayanganj Sadar",
        "Bandar",
        "Fatullah",
        "Kanchpur Highway",
        "Rupganj",
        "Shiddhirganj",
        "Sonargaon",
      ],
    },
    {
      name: "Narshindi",
      district: "Narshindi",
      thana: [
        "Belabo",
        "Narshindi Sadar",
        "Ghorashal",
        "Madhobdi",
        "Monohardi",
        "Palash",
        "Raipura",
        "Shibpur",
      ],
    },
    {
      name: "Natore",
      district: "Natore",
      thana: [
        "Bagatipara",
        "Natore Sadar",
        "Baraigram",
        "Gopalpur Pourosova",
        "Gurodaspur",
        "Lalpur",
        "Naldanga",
        "Singra",
      ],
    },
    {
      name: "Netrokona",
      district: "Netrokona",
      thana: [
        "Atpara",
        "Netrokona Sadar",
        "Barhatta",
        "Durgapur",
        "Kalmakanda",
        "Kendua",
        "Khaliajuri",
        "Madan",
        "Mohonganj",
        "Parbadhala",
      ],
    },
    {
      name: "Nilphamari",
      district: "Nilphamari",
      thana: [
        "Dimla",
        "Nilphamari Sadar",
        "Domar",
        "Jaldhaka",
        "Kishoreganj",
        "Saidpur",
      ],
    },
    {
      name: "Noakhali",
      district: "Noakhali",
      thana: [
        "Begamganj",
        "Noakhali Sadar",
        "Chatkhil",
        "Companyganj",
        "Hatiya",
        "Kabir Hat",
        "Senbagh",
        "Sonaimuri",
        "Subarnachar",
      ],
    },
    {
      name: "Pabna",
      district: "Pabna",
      thana: [
        "Ataikula (Pabna)",
        "Pabna Sadar",
        "Atgharia",
        "Bera",
        "Bhangura",
        "Chatmohar",
        "Ishwardi",
        "Santhia",
        "Sujanagar",
      ],
    },
    {
      name: "Panchgarh",
      district: "Panchgarh",
      thana: ["Atwari", "Panchgarh Sadar", "Boda", "Debiganj", "Tetulia"],
    },
    {
      name: "Patuakhali",
      district: "Patuakhali",
      thana: [
        "Bauphal",
        "Patuakhali Sadar",
        "Dashmina",
        "Dumki",
        "Galachipa",
        "Kalapara",
        "Mirzaganj",
        "Rangabali",
      ],
    },
    {
      name: "Pirojpur",
      district: "Pirojpur",
      thana: [
        "Bhandaria",
        "Pirojpur Sadar",
        "Indurkani",
        "Kawkhali",
        "Nazirpur",
        "Nesarabad",
        "Swarupkati",
      ],
    },
    {
      name: "Rajbari",
      district: "Rajbari",
      thana: [
        "(Goalanda Mor) Rajbari Office",
        "Rajbari Sadar",
        "Baliakandi",
        "Goalananda",
        "Kalukhali",
        "Pangsha",
      ],
    },
    {
      name: "Rajshahi",
      district: "Rajshahi",
      thana: [
        "Airport (Rajshahi)",
        "Rajshahi Sadar",
        "Bagha",
        "Bagmara",
        "Belpukur",
        "Boalia",
        "Chandrima Thana",
        "Charghat",
        "Damkura",
        "Durgapur",
        "Godagari",
        "Kashiadanga",
        "Katakhali",
        "Kornohar",
        "Matihar Thana",
        "Mohanpur",
        "Paba",
        "Puthia",
        "Rajpara",
        "Shah Makdam",
        "Tanore",
      ],
    },
    {
      name: "Rangamati",
      district: "Rangamati",
      thana: [
        "Bagaichhari",
        "Rangamati Sadar",
        "Barkal",
        "Belaichhari",
        "Juraichhari",
        "Kaptai",
        "Kawkhali Upazila",
        "Langadu",
        "Naniarchar",
        "Rajasthali",
      ],
    },
    {
      name: "Rangpur",
      district: "Rangpur",
      thana: [
        "Badarganj",
        "Rangpur Sadar",
        "Gangachara",
        "Kaunia",
        "Khulahati",
        "Mitapukur",
        "Piragacha",
        "Pirganj",
        "Shatibari",
        "Taraganj",
      ],
    },
    {
      name: "Shariatpur",
      district: "Shariatpur",
      thana: [
        "Bhedarganj",
        "Shariatpur Sadar",
        "Damudya",
        "Gosairhat",
        "Naria",
        "Sakhipur Upazila",
        "Zajira",
      ],
    },
    {
      name: "Shatkhira",
      district: "Shatkhira",
      thana: [
        "Assasuni",
        "Shatkhira Sadar",
        "Debhata",
        "Kalarao",
        "Kaliganj",
        "Patkelghata",
        "Shatkhira Sadar",
        "Shyamnagar",
        "Tala",
      ],
    },
    {
      name: "Sherpur",
      district: "Sherpur",
      thana: [
        "Jhenaigati",
        "Sherpur Sadar",
        "Nakla",
        "Nalitabari",
        "Sreebardi",
      ],
    },
    {
      name: "Sirajganj",
      district: "Sirajganj",
      thana: [
        "Belkuchi",
        "Sirajganj Sadar",
        "Chowhali",
        "Kamarkhanda",
        "Kazipur",
        "Raiganj",
        "Shahjadpur",
        "Tarash",
        "Ullapara",
      ],
    },
    {
      name: "Sunamganj",
      district: "Sunamganj",
      thana: [
        "Bishwamvapur",
        "Sunamganj Sadar",
        "Chhatak",
        "Derai",
        "Dharmapasha",
        "Dowarabazar",
        "Jagannathpur",
        "Jamalganj",
        "Moddonagar",
        "Shantiganj",
        "Sullah",
        "Tahirpur",
      ],
    },
    {
      name: "Sylhet",
      district: "Sylhet",
      thana: [
        "Balaganj",
        "Sylhet Sadar",
        "Beanibazar",
        "Bishanath",
        "Companyganj Upazila",
        "Fenchuganj",
        "Gobindaganj",
        "Golapganj",
        "Gowainghat",
        "Jalalabad",
        "Jalalabad Cantonment",
        "Jintiapur",
        "Kanaighat",
        "Osmaninagar",
        "Shahporan",
        "South Surma",
        "Zakiganj",
      ],
    },
    {
      name: "Tangail",
      district: "Tangail",
      thana: [
        "Basali",
        "Tangail Sadar",
        "Bhuapur",
        "Delduar",
        "Dhanbari",
        "Ghatali",
        "Gopalpur",
        "Kalihati",
        "Madhupur",
        "Mirzapur",
        "Nagarpur",
        "Sakhipur",
      ],
    },
    {
      name: "Thakurgaon",
      district: "Thakurgaon",
      thana: [
        "Baliadangi",
        "Thakurgaon Sadar",
        "Haripur",
        "Pirganj Upazila",
        "Ranisankali",
      ],
    },
  ];
};
